name: Generate Astro EPG

on:
  schedule:
    - cron: '0 15 * * 4'
    - cron: '0 15 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests pytz

      - name: Generate EPG
        run: |
          python epg.py || python epg.py

      - name: Compress EPG (max)
        run: |
          gzip -9 -f astro.xml

      - name: Commit changes
        run: |
          git config --global user.name "epg-bot"
          git config --global user.email "actions@github.com"

          git add astro.xml.gz

          git diff --cached --quiet || git commit -m "Auto update EPG"

          git push
